name: Build win64_x86

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  CMAKE_GENERATOR: MinGW Makefiles

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: 'MINGW64'
          cache: true
          install: >-
            make
            git
          pacboy: >-
            cmake:p
            gtest:p
            qt6:p
            gettext:p
            qt6-tools:p
            SDL2:p
            cpr:p
            spdlog:p
            toolchain:p
            openssl:p
            nsis:p

      - run: echo create symlink

      - run: git config --global core.autocrlf input

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B build -G "${{env.CMAKE_GENERATOR}}" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build build

      - name: Run unit tests
        run: build/fl_test

      - name: Build zip
        run: |
          cd build
          cpack -G ZIP

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: firelight-zip-win-x64
          path: build/Firelight-0.1.1-win64.zip

        # - name: Prepare artifact
        #   run: |
        #     cp /mingw64/bin/SDL2.dll build/
        #     cp /mingw64/bin/libcrypto-3-x64.dll build/
        #     ${GITHUB_WORKSPACE}/../Qt/6.6.2/mingw_64/bin/windeployqt build/firelight.exe --compiler-runtime


        # - name: Build
        #   # Build your program with the given configuration
        #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

        # - name: Test
        #   working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        # run: ctest -C ${{env.BUILD_TYPE}}

